theme: jekyll-theme-minimal
minimal_mistakes_skin: 
title: Sujan Balami
description: Ph.D. student | University of South Bohemia
author: Sujan Balami

social-network-links:
  twitter: BalamiSujan "https://twitter.com/BalamiSujan"

_publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
- README.md
- LICENSE.md
