theme: jekyll-theme-minimal
title: Sujan Balami
description: Ph.D. student | University of South Bohemia
author: Sujan Balami

social-network-links:
  twitter: BalamiSujan "https://twitter.com/BalamiSujan"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
- CONTRIBUTING.MD
- README.md
- LICENSE.md
- COPYING.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- ISSUE_TEMPLATE.md
- PULL_REQUEST_TEMPLATE.md
