project:
  type: website
  output-dir: "docs"

website:
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "Research"
        file: Research.qmd
      - text: "Tutorial"
        file: Tutorial.qmd
    right:
      - text: "CV"
        file: CV.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: cosmos
    css: styles.css

editor: visual
