project:
  type: website
  output-dir: "docs"

website:
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Research"
        href: Research.qmd
      - text: "Tutorial"
        href: Tutorial.qmd
        menu:
          - text: "SEED"
            href: Metagenome/SEED/SEED2.qmd
          - text: "SSU"
            href: Metagenome/SSU/SSU.qmd
          - text: QIIME2
            href: Metagenome/QIIME2/QIIME2.qmd
    right:
      - text: "CV"
        href: CV.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: cosmos
    css: styles.css

editor: visual
