---
title: "CV"
page-layout: full
title-block-banner: true
format:
  html: 
    theme: lux
    fontsize: 1.1em
    linestretch: 1.7
---

# Sujan Balami

Kathmandu, Nepal

balamisujan\@gmail.com \| https://sujanbalami.github.io

<a href="https://scholar.google.com/citations?user=G-BRVjMAAAAJ&hl=en" target="_blank"> Google Scholar profile </a>

## Work experiences

1.  **Postdoctoral Research Fellow** (2026/03 - present) \| Gyeongkuk National University \| Andong \| Republic of Korea

2.  **Postdoctoral Research Fellow** (2023/07 - 2026/03) \| Yunnan Key Laboratory of Forest Ecosystem Stability and Global Change \| Xishuangbanna Tropical Botanical Garden \| Chinese Academy of Sciences

3.  **Teaching assistant** (2022/09–2023/05) \| Amrit Campus, Institute of Science and Technology \| Tribhuvan University

4.  **Molecular lab technician** (2019/02–2019/04) \| University of South Bohemia, České Budějovice

5.  **Research assistant** (2018/02–2018/03) \| CzechGlobe–Global Change Research Institute, Czech Academy of Science, České Budějovice, Czech Republic

6.  **Teaching assistant** (2015/11–2017/09) \| Amrit Campus, Institute of Science and Technology \| Tribhuvan University

## Education

1.  **Ph.D. in Botany** (2017/10–2023/05) \| University of South Bohemia, České Budějovice, Czech Republic

2.  **M.Sc. in Botany** (2011/12–2015/10) \| Tribhuvan University, Kathmandu, Nepal

## Publications

1.  Vašutová M\*, Synková H, Choma M, **Balami S**, Šandová M, Vítovcová K. (2026). Limited restoration of plant microbiomes: Insights from fungal assemblages of a peatland dominant. Restoration Ecology e70521.
2.  Mo Y-X, Zou H, Hu H-X, Peñuelas J, Wang Z-P, Zheng B-X, Zheng B-X, Shi X-M, Li S, **Balami S**, Lu H-Z, Song L\*. (2026). Urbanization facilitates colonization and reshapes strangler-host networks: the fate of strangler figs in a tropical urban landscape and implications for management. Urban Forestry & Urban Greening 124: 129569.
3.  Dai Q, Yuan H, Mo Y-X, Li Y-C, He J-P, Jing ZP, Liu L, Chen Z-Y, Zhang Y-J, Bai Y, Shi X-M, **Balami S**, Xiao Y-X, Li S, Tan Z-H, Yang B, Song L\*. (2026). Applied nucleation triggers cross‐scale recovery in degraded tropical riparian corridors: a 20‐year multi‐scale assessment in China. RestorationEcology e70456.
4.  Chen Z-Y, Shi X-M, **Balami S**, Yuan H, Song L\*. (2026). Ecological restoration mitigates heavy metal pollution in rubber monocultures: Quantifying risk reduction and anthropogenic source control. Journal of Hazardous Materials Advances 22: 101203.
5.  Shi X-M, Liu A-X, Mo Y-X, **Balami S**, Qi J-H, Liu Y, Chen Z-Y, Song L\*. (2025) Coordinated yet allometric leaf-root biogeochemical niche dynamics underlies divergent growth predictability under N addition. Plant Soil 519: 853-866.
6.  **Balami S**, Mo Y-X, Hu H-X, Shi X-M, Song L\*. (2025) Soil enzyme stoichiometry indicates the alleviation of microbial carbon and nutrient limitations after forest restoration in rubber monocultures, Southwest China. Biotropica 57:e70104.
7.  Song L#, **Balami S**#, Gbadamassi GOD, Liu WG, Philippe T, Wanger TC, Edwards D, Wang MMH, Yang Y-P, Harrison R. (2025) Ecological restoration of rubber monocultures: strategies for biodiversity and ecosystem recovery in tropical regions. Integrative Conservation 2025: 1–9. \# equal first author.
8.  Shrestha S, **Balami S**, Vasutova M, Mandal T, & Raut JK. (2025) Ectomycorrhizal fungal communities of *Shorea robusta* along an elevation gradient. Mycorrhiza 35: 50.
9.  Manzoor, Qian D, Mo YX, **Balami S**, Wang C-J, Shi X-M, Zheng Y-J, Song L. (2025) Habitat and Density Effects on Tea Quality: A Microclimate and Nutrients Perspective. Agriculture Ecosystem and Environment 394: 109866.
10. Mo Y-X, Zou H, Hu H-X, Li S, Lu H, Pu X, Zhang Y, **Balami S**, Li Y, Hu T, Song L, Liu W. (2025) Strangler fig–host tree associations: Insights into the ecology and management of tropical urban green spaces. Plants People Planet 7:159–175.
11. Hu H, Mo Y, **Balami S**, Mendieta-Leiva G, Shen T, Haq SM, Song L. (2024) Combining critical transition indicator to compare the stable structure of epiphyte–host networks. Ecological Indicators 166:112470.
12. Adhikari HS, Magar GT, **Balami S**. (2024) *Laetiporus sulphureus* in the mid-hills of Central Nepal: ecology, ethnomycology and present status. Our Nature 22:10–18.
13. Awasthi M, Pokhrel C, You YH, **Balami S**, Kunwar R, Thapa S, Kim EJ, Park JW, Park JH, Lee JM, Kim YS. (2023) Comparative assessment of ethnobotany and antibacterial activity of *Moringa oleifera* Lam. in Nepal. Ethnobotany Research and Applications 25:1–3.
14. Chaudhary S, Magar GT, Shrestha S, **Balami S**. (2022) Peoples' Perception on Invasive Alien Plant Species of Ramdhuni Municipality, Sunsari District, Eastern Nepal. Amrit Research Journal 3:1–9.
15. **Balami S**, Vašutová M, Košnar J, Karki R, Khadka C, Tripathi G, Cudlín P. (2021) Soil fungal communities in abandoned agricultural land has not yet moved towards the seminatural forest. Forest Ecology and Management 491:119181.
16. **Balami S**, Vašutová M, Godbold D, Kotas P, Cudlín P. (2020) Soil fungal communities across land use types. iForest 13:548–558.
17. **Balami S**, Thapa LB, Jha SK. (2019) Effects of invasive *Ageratina adenophora* on mycelial growth of some important soil fungi. Songklanakarin Journal of Science & Technology 41:465–470.
18. Bhatta SP, Sharma KP, **Balami S**. (2018) Variation in carbon storage among tree species in the planted forest of Kathmandu, Central Nepal. Current Science 115:274–282.
19. **Balami S**, Thapa LB, Jha SK. (2017) Effect of invasive *Ageratina adenophora* on species richness and composition of saprotrophic and pathogenic soil fungi. BIOTROPIA-The Southeast Asian Journal of Tropical Biology 24:212–219.
20. **Balami S**, Thapa LB. (2017) Herbivory damage in native *Alnus nepalensis* and invasive *Ageratina adenophora*. Botanica Orientalis: Journal of Plant Science 11:7–11.
21. **Balami S**, Thapa LB, Jha SK. (2017) Sterilization effect of *Ageratina adenophora* invaded soil on root growth of native *Schima wallichii*. Physiological Ecology and Environmental Science 8:25–30. 17.
22. Jha SK\*, **Balami S**. (2016) Nutritive value of some wild edible macrofungi from Devdaha, Rupandehi district, Nepal. Journal of Biodiversity Conservation and Bioresource Management 2:21–27.

## Manuscripts

1.  **Balami S**, Hu H-X, Shi X-M, Mo Y-X, Byun C, Song L\*. Slower recovery of soil fungal communities: insights from \>20 years of tropical forest restoration in rubber monocultures. Restoration Ecology (Under review)
2.  **Balami S**, Shi X-M, Hu H-X, Mo Y-X, Byun C, Song L\*. Persistent recovery gap in soil fungal communities after vegetation restoration: a meta-analysis. Nature communications (Under review)
3.  **Balami S**, Song L. Arbuscular mycorrhizal fungal communities during restoration of rubber monoculture plantations. (In preparation)
4.  **Balami S**, Song L. Dynamics of soil microbial communities during secondary succession of abandoned rubber monocultures. (In preparation)
5.  **Balami S**, Vasutova M. Three new ectomycorrhizal fungal fruitbodies from Nepal. (In preparation)
6.  Yang Q-X, Yang B, Zhu X-A, Ma S, Hu Y-H, Chen Z-J, **Balami S**, Wu J, Song L. Terraces preserve more water with dimorphic water-uptake rubber trees than flatlands. Agriculture and Forest Meteorology (Under review)
7.  Thapa LB, Darji TB, Pathak S, Deuba R, **Balami S**\*, Pant G, Kaewchumnong K, Sinkkonen A. Response of native species to the invasive weeds *Ageratina adenophora* and *Chromolaena odorata* in central Nepal. Tropical Ecology (Under review)

## Conferences and symposia

- Paper presentation \| 24^th^ Ecology Conference of China 2025 \| Ecological Society of China

- Poster presentation \| Postdoctoral Conference 2023 \| Xishuangbanna Tropical Botanical Garden, Chinese Academy of Sciences

- Poster presentation \| Festival of Ecology 2020 \| British Ecological Society

- Papers and poster presentation \| International Conference on Biodiversity, Climate Change Assessment and Impacts on Livelihood 2017 \| Central Department of Botany

- Participation \| Interaction Program on Promotion of Scientific Concept 2017 \| Government of Nepal, Ministry of Science and Technology, B.P Koirala Memorial Planetarium, Observatory, and Science Museum Development Board

- Paper presentation \| The 7th National Conference on Science and Technology 2016 \| Nepal Academy of Science and Technology

- Participation \| National Symposium on Pesticides Pollution 2014 \| Kathmandu University and University Grant Commission, Nepal

## Grants and Fellowships

- The Yunnan Province Cai-Yun Postdoctoral Program 2024 - “Innovative project grant”

- "Zhi-Hui Yunnan” Program 2024 - Young Scientists & Young Entrepreneurs

- The Postdoctoral Talent Project of the Xishuangbanna Tropical Botanical Garden, Chinese Academy of Sciences

- Doctoral Scholarship (2017–2022) \| University of South Bohemia, České Budějovice, Czech Republic

## Awards and Honors

- Gold medal “category B” (2017) \| Ministry of Education, Science & Technology, Government of Nepal

- Professor B.D. Pandey Memorial Award (2016) \| Central Department of Botany, Tribhuvan University

- Gold Medal & Certificate of Merit (2011) \| Amrit Campus, Institute of Science & Technology, Tribhuvan University

## Professional activities

- Member \| Association of Tropical Biodiversity and Conservation (ATBC)

- Reviewer \| Applied Soil Ecology, Scientific Reports, Plant Ecology, Tropical Life Science Journal, Journal of Tropical Ecology, Journal of Chemical Ecology etc.

- Promotional editor (2022/11–2012) \| Nepal Journal of Biotechnology

- Editor (March 2017) \| Newsletter “Headlines Himalaya” from Environmental Graduates of Himalayas (EGH), Resource Himalaya Foundation

- Mentor \| 1 M.Sc. student and 2 B.Sc. Botany students of Amrit Campus, IOST, TU

- Internship (May 2019) \| University of Natural Resources and Life Sciences, Austria

- Vice-president (2017) \| Nature Conservation and Sustainable Development Society (NCDS), Nepal

- Member (2013) \| Botanical Student Society (BoSS), Central Department of Botany, TU
